from __future__ import annotations
import pygame
from typing import Protocol, TYPE_CHECKING
if TYPE_CHECKING:
    from core.game import Game

class Scene(Protocol):
    game: "Game"
    def on_enter(self) -> None: ...
    def on_exit(self) -> None: ...
    def handle_event(self, event: pygame.event.Event) -> None: ...
    def update(self, dt: float) -> None: ...
    def draw(self, screen: pygame.Surface) -> None: ...

class BaseScene:
    def __init__(self, game: "Game") -> None:
        self.game = game

    def on_enter(self) -> None: ...
    def on_exit(self) -> None: ...
    def handle_event(self, event: pygame.event.Event) -> None: ...
    def update(self, dt: float) -> None: ...
    def draw(self, screen: pygame.Surface) -> None: ...

    def _apply_brightness_overlay(self, screen: pygame.Surface) -> None:
        b = float(getattr(self.game.options, "brightness", 1.0))
        if b >= 0.999:
            return
        alpha = int((1.0 - b) * 200)
        overlay = pygame.Surface(screen.get_size(), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, alpha))
        screen.blit(overlay, (0, 0))
